# Generated by Django 4.0.5 on 2022-06-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_notes_alter_recipe_temp_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='temp_unit',
            field=models.CharField(choices=[('FA', 'Fahrenheit'), ('CE', 'Celsius'), ('TS', 'Teaspoon'), ('TB', 'Tablespoon'), ('CU', 'Cup'), ('GA', 'Gallon'), ('ML', 'Milliliter'), ('LI', 'Liter'), ('KG', 'Kilogram'), ('GR', 'Gram')], max_length=2),
        ),
    ]
