# Generated by Django 4.0.5 on 2022-06-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='by',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(null=True),
        ),
    ]
